version: "3.7"

services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env_docker

  todo_app:
    build:
      context: .
    command: uvicorn todo_app.main:web_app --host '0.0.0.0' --port 8000
    env_file:
      - .env_docker
    container_name: todo
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
      - statistic_app

  statistic_app:
    build:
      context: .
    command: uvicorn statistic.main:stat_app --host '0.0.0.0' --port 8080
    env_file:
      - .env_docker
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
