version: "3.7"

services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env_docker

  todo:
    build:
      context: .
    env_file:
      - .env_docker
    container_name: todo
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
